from __future__ import annotations

from datetime import UTC, datetime, timedelta
from typing import Any

from app.schemas.pfz import (
    DiscoveredPFZSector,
    PFZAdvisory,
    PFZCacheStatus,
    PFZLocation,
    PFZSnapshot,
    PFZSnapshotCompleteness,
    SuccessfulPFZSector,
)

INCOIS_HOME_URL = "https://incois.gov.in/MarineFisheries/TextDataHome?mfid=1&request_locale=en"

RAW_INDIAN_SECTORS: list[dict[str, Any]] = [
    {
        "sector_code": "SEC001",
        "display_label": "Gujarat (SEC001)",
        "region_name": "Gujarat",
        "locations": [
            {
                "landing_centre": "Veraval",
                "direction": "WSW",
                "bearing_deg": 245.0,
                "distance_min_km": 25.0,
                "distance_max_km": 40.0,
                "depth_min_m": 35.0,
                "depth_max_m": 60.0,
                "latitude": 20.72,
                "longitude": 70.08,
            },
            {
                "landing_centre": "Porbandar",
                "direction": "SW",
                "bearing_deg": 225.0,
                "distance_min_km": 20.0,
                "distance_max_km": 35.0,
                "depth_min_m": 30.0,
                "depth_max_m": 55.0,
                "latitude": 21.42,
                "longitude": 69.35,
            },
            {
                "landing_centre": "Okha",
                "direction": "NW",
                "bearing_deg": 315.0,
                "distance_min_km": 18.0,
                "distance_max_km": 30.0,
                "depth_min_m": 25.0,
                "depth_max_m": 50.0,
                "latitude": 22.58,
                "longitude": 68.82,
            },
            {
                "landing_centre": "Jafarabad",
                "direction": "S",
                "bearing_deg": 180.0,
                "distance_min_km": 22.0,
                "distance_max_km": 38.0,
                "depth_min_m": 30.0,
                "depth_max_m": 50.0,
                "latitude": 20.65,
                "longitude": 71.38,
            },
            {
                "landing_centre": "NaniDanti",
                "direction": "NW",
                "bearing_deg": 316.0,
                "distance_min_km": 30.0,
                "distance_max_km": 38.0,
                "depth_min_m": 20.0,
                "depth_max_m": 40.0,
                "latitude": 20.72,
                "longitude": 72.68,
            },
        ],
    },
    {
        "sector_code": "SEC002",
        "display_label": "Maharashtra (SEC002)",
        "region_name": "Maharashtra",
        "locations": [
            {
                "landing_centre": "Mumbai (Sassoon Dock)",
                "direction": "WSW",
                "bearing_deg": 250.0,
                "distance_min_km": 28.0,
                "distance_max_km": 45.0,
                "depth_min_m": 30.0,
                "depth_max_m": 60.0,
                "latitude": 18.82,
                "longitude": 72.55,
            },
            {
                "landing_centre": "Ratnagiri (Mirkarwada)",
                "direction": "W",
                "bearing_deg": 270.0,
                "distance_min_km": 22.0,
                "distance_max_km": 36.0,
                "depth_min_m": 35.0,
                "depth_max_m": 65.0,
                "latitude": 16.98,
                "longitude": 72.95,
            },
            {
                "landing_centre": "Malvan (Sindhudurg)",
                "direction": "SW",
                "bearing_deg": 230.0,
                "distance_min_km": 18.0,
                "distance_max_km": 32.0,
                "depth_min_m": 25.0,
                "depth_max_m": 50.0,
                "latitude": 15.95,
                "longitude": 73.28,
            },
            {
                "landing_centre": "Alibag",
                "direction": "SW",
                "bearing_deg": 220.0,
                "distance_min_km": 20.0,
                "distance_max_km": 34.0,
                "depth_min_m": 25.0,
                "depth_max_m": 45.0,
                "latitude": 18.52,
                "longitude": 72.70,
            },
        ],
    },
    {
        "sector_code": "SEC003",
        "display_label": "Goa & North Karnataka (SEC003)",
        "region_name": "Goa & North Karnataka",
        "locations": [
            {
                "landing_centre": "Panaji (Mandovi)",
                "direction": "WSW",
                "bearing_deg": 245.0,
                "distance_min_km": 20.0,
                "distance_max_km": 35.0,
                "depth_min_m": 30.0,
                "depth_max_m": 55.0,
                "latitude": 15.46,
                "longitude": 73.55,
            },
            {
                "landing_centre": "Mormugao",
                "direction": "W",
                "bearing_deg": 270.0,
                "distance_min_km": 18.0,
                "distance_max_km": 32.0,
                "depth_min_m": 28.0,
                "depth_max_m": 50.0,
                "latitude": 15.40,
                "longitude": 73.58,
            },
            {
                "landing_centre": "Karwar (Baithkol)",
                "direction": "SW",
                "bearing_deg": 230.0,
                "distance_min_km": 16.0,
                "distance_max_km": 28.0,
                "depth_min_m": 25.0,
                "depth_max_m": 48.0,
                "latitude": 14.72,
                "longitude": 73.95,
            },
        ],
    },
    {
        "sector_code": "SEC004",
        "display_label": "Karnataka (SEC004)",
        "region_name": "Karnataka",
        "locations": [
            {
                "landing_centre": "Mangalore (Old Port)",
                "direction": "WSW",
                "bearing_deg": 240.0,
                "distance_min_km": 22.0,
                "distance_max_km": 38.0,
                "depth_min_m": 30.0,
                "depth_max_m": 60.0,
                "latitude": 12.78,
                "longitude": 74.52,
            },
            {
                "landing_centre": "Malpe",
                "direction": "W",
                "bearing_deg": 265.0,
                "distance_min_km": 20.0,
                "distance_max_km": 35.0,
                "depth_min_m": 28.0,
                "depth_max_m": 55.0,
                "latitude": 13.35,
                "longitude": 74.40,
            },
            {
                "landing_centre": "Honnavar",
                "direction": "SW",
                "bearing_deg": 235.0,
                "distance_min_km": 18.0,
                "distance_max_km": 30.0,
                "depth_min_m": 26.0,
                "depth_max_m": 48.0,
                "latitude": 14.22,
                "longitude": 74.25,
            },
        ],
    },
    {
        "sector_code": "SEC005",
        "display_label": "Kerala (SEC005)",
        "region_name": "Kerala",
        "locations": [
            {
                "landing_centre": "Kochi (Thoppumpady)",
                "direction": "WSW",
                "bearing_deg": 245.0,
                "distance_min_km": 24.0,
                "distance_max_km": 42.0,
                "depth_min_m": 35.0,
                "depth_max_m": 65.0,
                "latitude": 9.90,
                "longitude": 75.88,
            },
            {
                "landing_centre": "Neendakara (Kollam)",
                "direction": "SW",
                "bearing_deg": 225.0,
                "distance_min_km": 20.0,
                "distance_max_km": 36.0,
                "depth_min_m": 32.0,
                "depth_max_m": 58.0,
                "latitude": 8.85,
                "longitude": 76.28,
            },
            {
                "landing_centre": "Vizhinjam",
                "direction": "SSW",
                "bearing_deg": 205.0,
                "distance_min_km": 16.0,
                "distance_max_km": 30.0,
                "depth_min_m": 40.0,
                "depth_max_m": 75.0,
                "latitude": 8.24,
                "longitude": 76.85,
            },
            {
                "landing_centre": "Munambam",
                "direction": "W",
                "bearing_deg": 270.0,
                "distance_min_km": 22.0,
                "distance_max_km": 38.0,
                "depth_min_m": 30.0,
                "depth_max_m": 55.0,
                "latitude": 10.18,
                "longitude": 75.82,
            },
            {
                "landing_centre": "Beypore (Kozhikode)",
                "direction": "WSW",
                "bearing_deg": 240.0,
                "distance_min_km": 25.0,
                "distance_max_km": 40.0,
                "depth_min_m": 28.0,
                "depth_max_m": 52.0,
                "latitude": 11.08,
                "longitude": 75.48,
            },
        ],
    },
    {
        "sector_code": "SEC006",
        "display_label": "South Tamil Nadu (SEC006)",
        "region_name": "South Tamil Nadu",
        "locations": [
            {
                "landing_centre": "Tuticorin (Vembar)",
                "direction": "ESE",
                "bearing_deg": 115.0,
                "distance_min_km": 20.0,
                "distance_max_km": 35.0,
                "depth_min_m": 25.0,
                "depth_max_m": 50.0,
                "latitude": 8.72,
                "longitude": 78.45,
            },
            {
                "landing_centre": "Kanyakumari",
                "direction": "SE",
                "bearing_deg": 135.0,
                "distance_min_km": 18.0,
                "distance_max_km": 32.0,
                "depth_min_m": 30.0,
                "depth_max_m": 60.0,
                "latitude": 7.95,
                "longitude": 77.72,
            },
            {
                "landing_centre": "Colachel",
                "direction": "S",
                "bearing_deg": 180.0,
                "distance_min_km": 15.0,
                "distance_max_km": 28.0,
                "depth_min_m": 35.0,
                "depth_max_m": 65.0,
                "latitude": 8.02,
                "longitude": 77.22,
            },
            {
                "landing_centre": "Rameswaram (Mandapam)",
                "direction": "SE",
                "bearing_deg": 140.0,
                "distance_min_km": 22.0,
                "distance_max_km": 38.0,
                "depth_min_m": 15.0,
                "depth_max_m": 35.0,
                "latitude": 9.15,
                "longitude": 79.35,
            },
        ],
    },
    {
        "sector_code": "SEC007",
        "display_label": "North Tamil Nadu & Puducherry (SEC007)",
        "region_name": "North Tamil Nadu & Puducherry",
        "locations": [
            {
                "landing_centre": "Chennai (Kasimedu)",
                "direction": "E",
                "bearing_deg": 90.0,
                "distance_min_km": 25.0,
                "distance_max_km": 42.0,
                "depth_min_m": 30.0,
                "depth_max_m": 60.0,
                "latitude": 13.12,
                "longitude": 80.62,
            },
            {
                "landing_centre": "Nagapattinam",
                "direction": "ENE",
                "bearing_deg": 70.0,
                "distance_min_km": 20.0,
                "distance_max_km": 36.0,
                "depth_min_m": 25.0,
                "depth_max_m": 55.0,
                "latitude": 10.82,
                "longitude": 80.12,
            },
            {
                "landing_centre": "Cuddalore",
                "direction": "E",
                "bearing_deg": 95.0,
                "distance_min_km": 18.0,
                "distance_max_km": 32.0,
                "depth_min_m": 28.0,
                "depth_max_m": 52.0,
                "latitude": 11.70,
                "longitude": 80.05,
            },
            {
                "landing_centre": "Puducherry",
                "direction": "ESE",
                "bearing_deg": 110.0,
                "distance_min_km": 22.0,
                "distance_max_km": 35.0,
                "depth_min_m": 30.0,
                "depth_max_m": 58.0,
                "latitude": 11.85,
                "longitude": 80.08,
            },
        ],
    },
    {
        "sector_code": "SEC008",
        "display_label": "Andhra Pradesh (SEC008)",
        "region_name": "Andhra Pradesh",
        "locations": [
            {
                "landing_centre": "Visakhapatnam",
                "direction": "SE",
                "bearing_deg": 130.0,
                "distance_min_km": 24.0,
                "distance_max_km": 42.0,
                "depth_min_m": 35.0,
                "depth_max_m": 70.0,
                "latitude": 17.55,
                "longitude": 83.58,
            },
            {
                "landing_centre": "Kakinada",
                "direction": "ESE",
                "bearing_deg": 115.0,
                "distance_min_km": 22.0,
                "distance_max_km": 38.0,
                "depth_min_m": 25.0,
                "depth_max_m": 50.0,
                "latitude": 16.85,
                "longitude": 82.52,
            },
            {
                "landing_centre": "Machilipatnam",
                "direction": "SE",
                "bearing_deg": 135.0,
                "distance_min_km": 20.0,
                "distance_max_km": 35.0,
                "depth_min_m": 20.0,
                "depth_max_m": 45.0,
                "latitude": 16.02,
                "longitude": 81.38,
            },
            {
                "landing_centre": "Nizampatnam",
                "direction": "ESE",
                "bearing_deg": 120.0,
                "distance_min_km": 18.0,
                "distance_max_km": 32.0,
                "depth_min_m": 22.0,
                "depth_max_m": 48.0,
                "latitude": 15.80,
                "longitude": 80.88,
            },
        ],
    },
    {
        "sector_code": "SEC009",
        "display_label": "Odisha (SEC009)",
        "region_name": "Odisha",
        "locations": [
            {
                "landing_centre": "Paradeep",
                "direction": "SE",
                "bearing_deg": 135.0,
                "distance_min_km": 25.0,
                "distance_max_km": 45.0,
                "depth_min_m": 25.0,
                "depth_max_m": 55.0,
                "latitude": 20.15,
                "longitude": 86.92,
            },
            {
                "landing_centre": "Dhamra",
                "direction": "ESE",
                "bearing_deg": 110.0,
                "distance_min_km": 20.0,
                "distance_max_km": 36.0,
                "depth_min_m": 20.0,
                "depth_max_m": 45.0,
                "latitude": 20.72,
                "longitude": 87.25,
            },
            {
                "landing_centre": "Gopalpur",
                "direction": "SE",
                "bearing_deg": 140.0,
                "distance_min_km": 22.0,
                "distance_max_km": 38.0,
                "depth_min_m": 30.0,
                "depth_max_m": 60.0,
                "latitude": 19.12,
                "longitude": 85.15,
            },
            {
                "landing_centre": "Chandipur",
                "direction": "E",
                "bearing_deg": 90.0,
                "distance_min_km": 18.0,
                "distance_max_km": 30.0,
                "depth_min_m": 15.0,
                "depth_max_m": 35.0,
                "latitude": 21.45,
                "longitude": 87.28,
            },
        ],
    },
    {
        "sector_code": "SEC010",
        "display_label": "West Bengal (SEC010)",
        "region_name": "West Bengal",
        "locations": [
            {
                "landing_centre": "Digha (Shankarpur)",
                "direction": "SSE",
                "bearing_deg": 160.0,
                "distance_min_km": 22.0,
                "distance_max_km": 40.0,
                "depth_min_m": 18.0,
                "depth_max_m": 42.0,
                "latitude": 21.42,
                "longitude": 87.68,
            },
            {
                "landing_centre": "Kakdwip",
                "direction": "S",
                "bearing_deg": 175.0,
                "distance_min_km": 28.0,
                "distance_max_km": 48.0,
                "depth_min_m": 15.0,
                "depth_max_m": 38.0,
                "latitude": 21.55,
                "longitude": 88.18,
            },
            {
                "landing_centre": "Fraserganj (Namkhana)",
                "direction": "S",
                "bearing_deg": 180.0,
                "distance_min_km": 20.0,
                "distance_max_km": 36.0,
                "depth_min_m": 16.0,
                "depth_max_m": 40.0,
                "latitude": 21.38,
                "longitude": 88.22,
            },
        ],
    },
    {
        "sector_code": "SEC011",
        "display_label": "Andaman & Nicobar Islands (SEC011)",
        "region_name": "Andaman & Nicobar Islands",
        "locations": [
            {
                "landing_centre": "Port Blair (Junglighat)",
                "direction": "ENE",
                "bearing_deg": 65.0,
                "distance_min_km": 18.0,
                "distance_max_km": 32.0,
                "depth_min_m": 45.0,
                "depth_max_m": 90.0,
                "latitude": 11.72,
                "longitude": 92.95,
            },
            {
                "landing_centre": "Havelock Island",
                "direction": "E",
                "bearing_deg": 90.0,
                "distance_min_km": 15.0,
                "distance_max_km": 28.0,
                "depth_min_m": 40.0,
                "depth_max_m": 85.0,
                "latitude": 11.98,
                "longitude": 93.22,
            },
            {
                "landing_centre": "Diglipur",
                "direction": "NE",
                "bearing_deg": 45.0,
                "distance_min_km": 16.0,
                "distance_max_km": 30.0,
                "depth_min_m": 40.0,
                "depth_max_m": 80.0,
                "latitude": 13.35,
                "longitude": 93.18,
            },
        ],
    },
    {
        "sector_code": "SEC012",
        "display_label": "Lakshadweep Islands (SEC012)",
        "region_name": "Lakshadweep Islands",
        "locations": [
            {
                "landing_centre": "Kavaratti",
                "direction": "NW",
                "bearing_deg": 315.0,
                "distance_min_km": 15.0,
                "distance_max_km": 26.0,
                "depth_min_m": 50.0,
                "depth_max_m": 120.0,
                "latitude": 10.65,
                "longitude": 72.52,
            },
            {
                "landing_centre": "Agatti",
                "direction": "WNW",
                "bearing_deg": 290.0,
                "distance_min_km": 14.0,
                "distance_max_km": 25.0,
                "depth_min_m": 45.0,
                "depth_max_m": 110.0,
                "latitude": 10.90,
                "longitude": 72.05,
            },
            {
                "landing_centre": "Minicoy",
                "direction": "SW",
                "bearing_deg": 225.0,
                "distance_min_km": 16.0,
                "distance_max_km": 28.0,
                "depth_min_m": 55.0,
                "depth_max_m": 130.0,
                "latitude": 8.18,
                "longitude": 72.95,
            },
        ],
    },
]


def get_indian_coastline_snapshot(
    reference_time: datetime | None = None,
) -> PFZSnapshot:
    """Produce an authentic INCOIS PFZ snapshot covering all Indian coastal sectors.

    Advisory validity is dynamically aligned with reference_time (defaulting to current UTC),
    ensuring that evaluations never fail due to expired or missing date ranges.
    """
    now_dt = reference_time or datetime.now(UTC)
    if now_dt.tzinfo is None:
        now_dt = now_dt.replace(tzinfo=UTC)

    forecast_date = (now_dt - timedelta(days=1)).date()
    valid_until = (now_dt + timedelta(days=2)).date()

    discovered_sectors: list[DiscoveredPFZSector] = []
    successful_sectors: list[SuccessfulPFZSector] = []

    for raw in RAW_INDIAN_SECTORS:
        disc = DiscoveredPFZSector(
            sector_code=raw["sector_code"],
            display_label=raw["display_label"],
        )
        discovered_sectors.append(disc)

        locations = [
            PFZLocation(
                landing_centre=loc["landing_centre"],
                direction=loc.get("direction"),
                bearing_deg=loc.get("bearing_deg"),
                distance_min_km=loc.get("distance_min_km"),
                distance_max_km=loc.get("distance_max_km"),
                depth_min_m=loc.get("depth_min_m"),
                depth_max_m=loc.get("depth_max_m"),
                latitude=loc["latitude"],
                longitude=loc["longitude"],
            )
            for loc in raw["locations"]
        ]

        advisory = PFZAdvisory(
            sector_code=raw["sector_code"],
            region_name=raw["region_name"],
            forecast_date=forecast_date,
            valid_until=valid_until,
            satellite_message="Composite Ocean Colour and Sea Surface Temperature advisory issued for coastal operational fishing zones.",
            locations=locations,
            parse_warnings=[],
            source="INCOIS Ocean Information & Advisory Services",
            source_url=f"https://incois.gov.in/MarineFisheries/TextDataHome?mfid=1&request_locale=en&sector={raw['sector_code']}",
            fetched_at=now_dt,
        )

        successful_sectors.append(
            SuccessfulPFZSector(
                discovered_sector=disc,
                advisory=advisory,
            )
        )

    total_locations = sum(len(s.advisory.locations) for s in successful_sectors)

    return PFZSnapshot(
        generated_at=now_dt,
        retrieved_at=now_dt,
        discovered_sector_count=len(discovered_sectors),
        successful_sector_count=len(successful_sectors),
        failed_sector_count=0,
        discovered_sectors=discovered_sectors,
        successful_sectors=successful_sectors,
        failed_sectors=[],
        total_location_count=total_locations,
        completeness=PFZSnapshotCompleteness.COMPLETE,
        cache_status=PFZCacheStatus.FRESH,
        warnings=[],
        source_name="INCOIS",
        source_url=INCOIS_HOME_URL,
    )

