import {
  OceanConditions,
  DecisionData,
  AgentStep,
  EvidenceSource,
  ChatMessage,
  AlertItem,
  MapMarker,
  UserModeConfig,
  AgentPipelineInfo,
} from "./types";

export const userModeConfigs: Record<string, UserModeConfig> = {
  fisherman: {
    id: "fisherman",
    label: "Fisherman",
    roleDescription: "Coastal safety, fishing zone access & live wave advisory",
    badgeColor: "bg-cyan/10 text-cyan border-cyan/30",
    defaultPrompt: "Can I go fishing from Mumbai harbour tomorrow morning?",
    features: ["Wave & swell height alerts", "Fishing zone restrictions", "Nearest safe harbor guidance"],
  },
  authority: {
    id: "authority",
    label: "Port & Coastal Authority",
    roleDescription: "Surveillance, vessel traffic, storm warnings & zone enforcement",
    badgeColor: "bg-avoid/10 text-avoid border-avoid/30",
    defaultPrompt: "Check harbor entrance congestion and coastal patrol compliance in Sector 4.",
    features: ["Vessel clearance tracking", "Storm broadcast tools", "Exclusive Economic Zone surveillance"],
  },
  researcher: {
    id: "researcher",
    label: "Marine Researcher",
    roleDescription: "Sea surface temperature anomalies, salinity & coral monitoring",
    badgeColor: "bg-go/10 text-go border-go/30",
    defaultPrompt: "Analyze sea surface temperature anomalies off the Konkan coast over the past 7 days.",
    features: ["Satellite thermal imagery feeds", "Chlorophyll concentration maps", "Longitudinal climate trends"],
  },
  operator: {
    id: "operator",
    label: "Fleet / Cargo Operator",
    roleDescription: "Route optimization, fuel efficiency & rough sea avoidance",
    badgeColor: "bg-wait/10 text-wait border-wait/30",
    defaultPrompt: "Evaluate optimal commercial shipping route from JNPT to Kandla around weather front.",
    features: ["Route risk matrix", "Estimated fuel vs delay calculator", "AIS live collision warning"],
  },
};

export const mockOceanConditions: OceanConditions = {
  waveHeightM: 1.4,
  windSpeedKmh: 18,
  windDirection: "WSW 240°",
  seaSurfaceTempC: 27.8,
  rainProbabilityPct: 20,
  visibilityKm: 12.4,
  tideLevelM: 1.85,
  currentSpeedKnots: 2.1,
};

export const mockDecision: DecisionData = {
  status: "GO",
  headline: "Safe Maritime Conditions Detected",
  riskScore: 24,
  location: "Mumbai Coastal Sector (0-15 NM)",
  summary: "Wave swells and surface winds remain well within safe operating thresholds for all vessel types.",
  recommendation: "Favorable conditions for departure until 16:00 IST. Monitor evening wind surge advisory.",
  riskFactors: [
    { label: "Wave Height", value: "1.4 m (Safe)", percent: 28, level: "GO" },
    { label: "Wind Velocity", value: "18 km/h (Moderate)", percent: 32, level: "GO" },
    { label: "Precipitation Risk", value: "20% (Low)", percent: 18, level: "GO" },
    { label: "Visibility", value: "12.4 km (Clear)", percent: 12, level: "GO" },
  ],
  updatedAt: "2 min ago",
};

export const mockWaitDecision: DecisionData = {
  status: "WAIT",
  headline: "Moderate Coastal Risk — Hold Advisory",
  riskScore: 68,
  location: "Konkan Offshore Sector B",
  summary: "Developing squall line 18 NM offshore. Strong gusts and swell heights increasing rapidly.",
  recommendation: "Delay departure by 3–4 hours until satellite passes confirm squall front dissipation.",
  riskFactors: [
    { label: "Wave Height", value: "2.8 m (Elevated)", percent: 72, level: "WAIT" },
    { label: "Wind Gusts", value: "42 km/h (Strong)", percent: 78, level: "WAIT" },
    { label: "Precipitation Risk", value: "85% (Squall Expected)", percent: 85, level: "AVOID" },
    { label: "Visibility", value: "4.2 km (Restricted)", percent: 62, level: "WAIT" },
  ],
  updatedAt: "Just now",
};

export const mockAvoidDecision: DecisionData = {
  status: "AVOID",
  headline: "Severe Weather Warning — No Sail",
  riskScore: 92,
  location: "Central Arabian Sea Cyclone Track",
  summary: "Severe cyclonic system active with sustained winds exceeding 65 km/h and wave heights above 4.5m.",
  recommendation: "Strict port closure in effect. All craft must return to shore immediately.",
  riskFactors: [
    { label: "Wave Height", value: "4.8 m (Dangerous)", percent: 96, level: "AVOID" },
    { label: "Wind Speed", value: "68 km/h (Gale Force)", percent: 94, level: "AVOID" },
    { label: "Precipitation", value: "100% (Torrential)", percent: 99, level: "AVOID" },
    { label: "Storm Surge", value: "+1.9 m over baseline", percent: 88, level: "AVOID" },
  ],
  updatedAt: "1 min ago",
};

export const mockAgentSteps: AgentStep[] = [
  { name: "Marine Data Agent", status: "completed", detail: "Ingested 4 INCOIS buoys & tide tables", latencyMs: 140 },
  { name: "Weather Agent", status: "completed", detail: "ECMWF & GFS ensemble processed", latencyMs: 220 },
  { name: "Ocean Analytics Agent", status: "completed", detail: "Bathymetry & current vector solved", latencyMs: 310 },
  { name: "GIS & Spatial Agent", status: "completed", detail: "Restricted zones & bathymetry overlayed", latencyMs: 180 },
  { name: "Risk Assessment Agent", status: "processing", detail: "Synthesizing multi-agent safety score...", latencyMs: 460 },
];

export const mockEvidenceSources: EvidenceSource[] = [
  {
    id: "src-1",
    sourceName: "INCOIS Coastal Buoy Array (CB-04)",
    category: "ocean",
    label: "Wave & swell spectrum",
    metric: "Hs: 1.4m | Tp: 7.2s",
    confidence: 98,
    fetchedAgo: "2 min ago",
    status: "live",
  },
  {
    id: "src-2",
    sourceName: "Copernicus Sentinel-3 SLSTR",
    category: "satellite",
    label: "Sea Surface Temperature Field",
    metric: "27.8°C (±0.2°C anomaly)",
    confidence: 94,
    fetchedAgo: "14 min ago",
    status: "verified",
  },
  {
    id: "src-3",
    sourceName: "IMD Doppler Weather Radar (Mumbai)",
    category: "weather",
    label: "Precipitation Reflectivity (dBZ)",
    metric: "18 dBZ (Scattered light cloud)",
    confidence: 96,
    fetchedAgo: "5 min ago",
    status: "live",
  },
  {
    id: "src-4",
    sourceName: "DGLL Marine AIS Receiver Grid",
    category: "ais",
    label: "Vessel Density & Route Congestion",
    metric: "14 active vessels in 5 NM corridor",
    confidence: 99,
    fetchedAgo: "Just now",
    status: "live",
  },
];

export const mockChatMessages: ChatMessage[] = [
  {
    id: "m1",
    role: "user",
    text: "Can I go fishing from Mumbai harbour tomorrow morning?",
    timestamp: "09:02 AM",
    userMode: "fisherman",
  },
  {
    id: "m2",
    role: "assistant",
    text: "Here is your live multi-agent marine assessment for Mumbai Coastal Sector (0-15 NM). Conditions are evaluated across meteorological radar, oceanographic buoys, and coastal traffic.",
    decision: mockWaitDecision,
    agents: mockAgentSteps,
    sources: mockEvidenceSources,
    timestamp: "09:02 AM",
  },
];

export const mockAlerts: AlertItem[] = [
  {
    id: "a1",
    severity: "high",
    title: "Cyclone Watch — System Intensification",
    region: "Arabian Sea (Sector West-Central)",
    issuedAt: "25 min ago",
    description: "Deep depression tracking north-northeast with squally winds 55-65 km/h gusting to 75 km/h. Small craft advisory in effect.",
    type: "cyclone",
    targetModes: ["fisherman", "authority", "operator"],
    coordinates: "18.42° N, 71.18° E",
  },
  {
    id: "a2",
    severity: "medium",
    title: "High Wave Swell Advisory",
    region: "Konkan Coast & Ratnagiri",
    issuedAt: "1 hour ago",
    description: "Swell surge up to 2.8m expected during spring high tide between 14:00 and 19:00 IST. Caution advised near rocky shoals.",
    type: "wave",
    targetModes: ["fisherman", "operator"],
    coordinates: "16.99° N, 73.28° E",
  },
  {
    id: "a3",
    severity: "low",
    title: "Marine Protected Zone Seasonal Cap",
    region: "Gulf of Khambhat Marine Sanctuary",
    issuedAt: "4 hours ago",
    description: "Seasonal trawling restrictions operational. Scientific survey vessels require prior digital radio clearance.",
    type: "zone",
    targetModes: ["authority", "researcher"],
    coordinates: "21.28° N, 72.15° E",
  },
  {
    id: "a4",
    severity: "medium",
    title: "Anomalous Thermal Bloom Alert",
    region: "Goa Offshore Transect",
    issuedAt: "6 hours ago",
    description: "MODIS thermal sensors report SST +1.6°C above historical baseline. Possible micro-algal bloom formation under observation.",
    type: "biological",
    targetModes: ["researcher"],
    coordinates: "15.39° N, 73.74° E",
  },
];

export const mockMapMarkers: MapMarker[] = [
  {
    id: "u1",
    type: "user",
    label: "Your Craft (ORCA-1)",
    subtitle: "Speed: 8.4 kn | Hdg: 240°",
    x: 44,
    y: 52,
    details: { speed: "8.4 kn", heading: "240° WSW", waveHeight: "1.4m" },
    visibleForModes: ["fisherman", "authority", "researcher", "operator"],
  },
  {
    id: "h1",
    type: "hazard",
    label: "Squall & Storm Cell",
    subtitle: "Wind 42 km/h | 2.8m Swell",
    x: 68,
    y: 28,
    severity: "high",
    details: { warning: "Squall cell propagating ENE at 14 kn", waveHeight: "2.8m" },
    visibleForModes: ["fisherman", "authority", "operator"],
  },
  {
    id: "h2",
    type: "hazard",
    label: "Submerged Shoal Hazard",
    subtitle: "Min Depth: 2.1m Charted",
    x: 24,
    y: 68,
    severity: "medium",
    details: { warning: "Shallow reef boundary", waveHeight: "1.2m" },
    visibleForModes: ["fisherman", "operator"],
  },
  {
    id: "v1",
    type: "vessel",
    label: "Fishing Fleet Alpha (6 vessels)",
    subtitle: "Target: Tuna Shoal",
    x: 58,
    y: 44,
    details: { speed: "4.2 kn", heading: "180° S" },
    visibleForModes: ["fisherman", "authority", "operator"],
  },
  {
    id: "r1",
    type: "route",
    label: "Recommended Safe Channel",
    subtitle: "Risk Score: Low (18/100)",
    x: 38,
    y: 40,
    details: { warning: "Cleared by GIS & Risk Agent" },
    visibleForModes: ["fisherman", "operator", "authority"],
  },
  {
    id: "s1",
    type: "sensor",
    label: "INCOIS Buoy CB-04",
    subtitle: "Temp: 27.8°C | Salinity: 35.2 PSU",
    x: 72,
    y: 62,
    details: { temperature: "27.8°C", waveHeight: "1.4m" },
    visibleForModes: ["researcher", "authority"],
  },
  {
    id: "p1",
    type: "port",
    label: "Mumbai Port & JNPT Channel",
    subtitle: "Berth Status: Active",
    x: 32,
    y: 35,
    details: { warning: "VHF Ch 12 monitoring" },
    visibleForModes: ["authority", "operator"],
  },
];

export const mockAgentPipelines: AgentPipelineInfo[] = [
  {
    id: "agent-marine-data",
    name: "Marine Data Agent",
    role: "Buoy telemetry ingestion, tide table synchronization & bathymetric indexing",
    endpoint: "https://api.orca.marine/v1/agents/marine-data",
    avgLatency: "140 ms",
    status: "operational",
    dataFeed: "INCOIS, NOAA NDBC, GEBCO Grid",
    lastSync: "30s ago",
    accuracy: "99.4%",
  },
  {
    id: "agent-weather",
    name: "Meteorological Weather Agent",
    role: "High-resolution Doppler radar, GFS wind vector & precipitation modeling",
    endpoint: "https://api.orca.marine/v1/agents/weather",
    avgLatency: "210 ms",
    status: "operational",
    dataFeed: "IMD Radar API, ECMWF OpenData",
    lastSync: "45s ago",
    accuracy: "97.8%",
  },
  {
    id: "agent-ocean",
    name: "Ocean Analytics Agent",
    role: "Current dynamics, thermal cline analysis & wave-surge physics engine",
    endpoint: "https://api.orca.marine/v1/agents/ocean-analytics",
    avgLatency: "310 ms",
    status: "operational",
    dataFeed: "Copernicus Marine Marine Service (CMEMS)",
    lastSync: "1m ago",
    accuracy: "98.6%",
  },
  {
    id: "agent-gis",
    name: "GIS & Spatial Intelligence Agent",
    role: "Restricted maritime boundary checks, shipping corridors & reef polygon collision",
    endpoint: "https://api.orca.marine/v1/agents/gis",
    avgLatency: "180 ms",
    status: "operational",
    dataFeed: "OpenSeaMap, Indian Coast Guard Zones",
    lastSync: "2m ago",
    accuracy: "99.9%",
  },
  {
    id: "agent-risk",
    name: "Synthesized Risk & Decision Agent",
    role: "Multi-agent consensus scoring, confidence calibration & GO/WAIT/AVOID arbiter",
    endpoint: "https://api.orca.marine/v1/agents/risk-decision",
    avgLatency: "440 ms",
    status: "operational",
    dataFeed: "Internal ORCA Multi-Agent Arbitration",
    lastSync: "Just now",
    accuracy: "99.1%",
  },
];

export const mockHourlyForecast = [
  { time: "06:00", wave: 1.2, wind: 14, risk: 20 },
  { time: "09:00", wave: 1.4, wind: 18, risk: 24 },
  { time: "12:00", wave: 1.9, wind: 26, risk: 45 },
  { time: "15:00", wave: 2.7, wind: 38, risk: 72 },
  { time: "18:00", wave: 2.4, wind: 32, risk: 65 },
  { time: "21:00", wave: 1.8, wind: 22, risk: 35 },
  { time: "00:00", wave: 1.5, wind: 16, risk: 25 },
];